---
title: Matías Zalazar
url: "https://matzalazar.com"
baseurl: ""
lang: es

header_pages:
  - index.md
  - articles.md
  - projects.md
  - about.md

footer: 'Podés escribirme un <a href="mailto:matias.zalazar@icloud.com">mail</a> o conectarme en <a href="https://www.linkedin.com/in/matzalazar/">linkedin</a>'

# Nuevo tema: cyborg (terminal moderno refinado)
style: cyborg

# Analytics
goatcounter: matzalazar

collections:
  articles:
    output: true 
    permalink: /article/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
