title: Matías Zalazar
url: "https://matzalazar.com"
baseurl: ""

header_pages:
  - index.md
  - articles.md
  - log.md
  - about.md

footer: 'Podés escribirme un <a href="mailto:matias.zalazar@icloud.com">mail</a> o conectarme en <a href="https://www.linkedin.com/in/matzalazar/">linkedin</a>'

collections:
  articles:
    output: true 
    permalink: /article/:name/
  logs:
    output: true
    permalink: /log/:name/

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
